### ISSUE TITLE
Remove `MEDUSA.config` and `startVue`

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#4765]
<details open>
<summary>These are the pages that still reference <code>MEDUSA.config</code>:</summary>

- [ ] config_backuprestore.mako
- [ ] config_general.mako
- [ ] config_providers.mako
- [ ] config_search.mako
- [x] manage_episodeStatuses.mako (#6748)
- [ ] schedule.mako
- [x] root-dirs.vue (#4718)

</details>

<details>
<summary>These pages still have the <code>startVue()</code> wrapper:<br>
(All done! 🎉)</summary>

- [x] home.mako (#4889)
- [x] 404.mako (#4937)
- [x] 500.mako (#4937)
- [x] errorlogs.mako (#4937)
- [x] genericMessage.mako (#4937)
- [x] history,mako (#4937)
- [x] home_postprocess.mako (#4889)
- [x] IRC.mako (#4937)
- [x] manage_backlogOverview.mako (#4937)
- [x] manage_episodeStatuses.mako (#4937)
- [x] manage_failedDownloads.mako (#4937)
- [x] manage_subtitleMissed.mako (#4937)
- [x] manage_subtitleMissedPP.mako (#4937)
- [x] manage.mako (#4937)
- [x] markdown.mako (#4937)
- [x] restart.mako (#4937)
- [x] schedule.mako (#4937)
- [x] snatchSelection.mako (#4888)
- [x] status.mako (#4889)
- [x] testRename.mako (#4937)
- [x] ~trendingShows.mako~ (#4937 **unused file, removed**)
- [x] viewlogs.mako (#4937)

</details>

### @OmgImAlexis todo:
- [ ] Vueify home page (inc all layouts poster, small, banner, simple) #5345.
With this, remove the mako code, so we don't list shows twice. (make and apiv2)
- [ ] Vueify displayShow. High in the list, as there currently is a bug with bigger shows. #5856 #5222 
- [ ] Move editShow to .vue component. #4486 
- [ ] Move config - notification to .vue component #5580 
- [ ] Move config - search to .vue component (not started)
- [ ] Vueify config - general i started but can't finish #5617 + move to .vue component
- [ ] Vueify config - provider (not started)
- [ ] Implement & document framework for web sockets updates.
- [ ] Vueify config - backup / restore #5556
