### ISSUE TITLE
[ WIKI ] TODO list for rebranding wiki pages

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#613]
The following pages need to be changed. I've separated the list in content (information) and images (screenshots).
### Content
- [ ] https://github.com/pymedusa/SickRage/wiki/What-is-Medusa%3F/_edit: Update feature list
### Images
- [ ] https://github.com/pyMedusa/SickRage/wiki/What-is-Medusa%3F#screenshots
- [ ] https://github.com/pyMedusa/SickRage/wiki/Settings-explained
- [ ] https://github.com/pyMedusa/SickRage/wiki/Show-settings-explained
- [ ] https://github.com/pyMedusa/SickRage/wiki/Remaining-settings-explained
- [ ] https://github.com/pyMedusa/SickRage/wiki/MetaData
- [ ] https://github.com/pyMedusa/SickRage/wiki/Post-Processing
- [ ] https://github.com/pyMedusa/SickRage/wiki/Scene-exceptions-and-numbering
- [ ] https://github.com/pyMedusa/SickRage/wiki/SSL-Errors
- [ ] https://cdn.pymedusa.com/index.html

**Comment by OmgImAlexis** [comment]
Also needs doing: https://github.com/pymedusa/SickRage/issues/695
