### ISSUE TITLE
General guessit induced/related issues

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#810]
TODO:
- [x] [Wrong season](https://github.com/pymedusa/Medusa/issues/810#issuecomment-254490731)
- [x] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-255558111)
- [x] [Wrong ep title and air date](https://github.com/pymedusa/Medusa/issues/810#issuecomment-255858187)
- [x] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-256492077)
- [x] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-257167849)
- [x] [Scene release numbering not detected ](https://github.com/pymedusa/Medusa/issues/810#issuecomment-258586604)
- [ ] https://github.com/pymedusa/Medusa/issues/810#issuecomment-255877018
- [x] [Wrong title](https://github.com/pymedusa/Medusa/issues/1493#issuecomment-258853023) 
- [ ] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-259827803)
- [x] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-261100944)
- [ ] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-261377027)
- [ ] [Wrong numbering](https://github.com/pymedusa/Medusa/issues/810#issuecomment-261583833)
- [x] [Wrong numbering](https://github.com/pymedusa/Medusa/issues/810#issuecomment-261721029)
- [ ] [Wrong Title](https://github.com/pymedusa/Medusa/issues/810#issuecomment-261752356) 
- [ ] [Wrong Title](https://github.com/pymedusa/Medusa/issues/810#issuecomment-263158795)
- [ ] [Wrong Title](https://github.com/pymedusa/Medusa/issues/810#issuecomment-264337236)
- [ ] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-264665613)
- [ ] [Wrong release group](https://github.com/pymedusa/Medusa/issues/810#issuecomment-264722778)
- [ ] [Wrong episode_details](https://github.com/pymedusa/Medusa/issues/810#issuecomment-266252346)

**Comment by medariox** [comment]
Release group is just BRISK, without [PRiME].

**Comment by ratoaq2** [comment]
What's the full name? Or it's just that?

With a show name it works just fine:
```
? Show.Name.HDTV.x264-BRISK[PRiME]
: title: Show Name
  format: HDTV
  video_codec: h264
  release_group: BRISK
  type: episode
```

**Comment by fernandog** [comment]
`Bones.S11E22.720p.HDTV.x264-BRISK[PRiME]`

**Comment by medariox** [comment]
@fernandog 
No issue here with that exact episode.

**Comment by fernandog** [comment]
weird:

![image](https://cloud.githubusercontent.com/assets/2620870/17084571/6ba84a1c-5197-11e6-886c-dd8967ac2244.png)

**Comment by fernandog** [comment]
What about this?

RN: Suits.S06E03.Back.on.the.Map.1080p.USA.WEBRip.AAC2.0.x264-BTW-BUYMORE
Group: BTW-BUYMORE

**Comment by duramato** [comment]
Declassified.Untold.Stories.of.American.Spies.S01E02.The.Hunt.for.Saddam.720p.HDTV.x264-DHD.VR56.eztv.mkv
group: DHD.VR56
Declassified.Untold.Stories.of.American.Spies.S01E02.The.Hunt.for.Saddam.720p.HDTV.x264-DHD.VR56
group: DHD.VR56

Stranger.Things.S01e01[Mux.-.720p.-.H264.-.Ita.Eng.Ac3.-.Sub.Ita.Eng]DLMux.By.GiuseppeiCV.Littlelinx
group GiuseppeiCV
should be: GiuseppeiCV.Littlelinx @medariox 

Stranger.Things.-.S01E01.-.Das.Verschwinden.des.Will.Byers.-.mkv.-.by.Videomann
group: None
should be Videomann

[BinSearch] :: [378d2ca] Unable to match [.160715_01.Queen.of.the.South.S01E05.720p.WEB-DL.DD5.1.H.264-VietHD.].--."160715_01.Queen.of.the.South.S01E05.720p.WEB-DL.DD5.1.H.264-VietHD.nfo" to a show in your database. Parser result: "160715 01 Queen of the South - S01E05 [GROUP: VietHD.nfo] [ABD: False] [ANIME: False]

should be:  {show: "Queen of the South" , group: "VietHD"}

[drunkenslug] :: [378d2ca] Unable to match [BakedFish].Love.Live!.Sunshine!!.-.05.[720p][AAC].mp4.[1/6].-."[BakedFish].Love.Live!.Sunshine!!.-.05.[720p][AAC].mp4" to a show in your database. Parser result: Love Live! Sunshine!! -  [ABS: [5, 6]] [ANIME VER: -1] [GROUP: BakedFish] [ABD: False] [ANIME: True]

abs nr should be only 5

[drunkenslug] :: [378d2ca] Unable to match [HorribleSubs].Hatsukoi.Monster.-.05.[1080p].[01/22].-."[HorribleSubs].Hatsukoi.Monster.-.05.[1080p].mkv.001" to a show in your database. Parser result: " -  [ABS: [5, 22]] [ANIME VER: -1] [GROUP: HorribleSubs] [ABD: False] [ANIME: True]

same as previous one, abs nr shouldbe 5

[Demonoid] :: [378d2ca] Unable to match BBC.Countryfile.Sp.ring.Diaries.Serie.s.1.5of5.A.Window..on.Summer.720p.HDT.V.x264.AAC.MVGroup..org.mp4 to a show in your database. Parser result: BBC Countryfile Sp ring Diaries Serie s - E01E05 [GROUP: MVGroup..org] [ABD: False] [ANIME: False]
wrong title should be " BBC Countryfile Sp ring Diaries"
**Note**: don't know if its fixable becouse of the spaces

**Comment by duramato** [comment]
`Panorama.2016.07.18.Trumps.Angry.America.EN.SUB.MPEG4.x264-WEBRIP.MPup.Trump's.Angry.America`
and
`Panorama.2016.07.18.Trumps.Angry.America.EN.SUB.HEVC.x265.WEBRIP.[MPup].|.Trump's.Angry.America.|`
and 
`Panorama.2016.07.18.Trumps.Angry.America.EN.SUB.HEVC.x265.WEBRIP.MPup.Trump's.Angry.America`
_**Group detected:**_  _MPup.Trump's.Angry_   or `MPup].|.Trump's.Angry` depending on the case
**Should be:** [MPup] and MPup depending on the example

**Comment by fernandog** [comment]
BUYMORE still isn't worked. Episode aired 2 days ago:
S*.S06E05.720p.HDTV.x264-KILLERS-BUYMORE	KILLERS-BUYMORE

**Comment by duramato** [comment]
`The.Get.Down.S01EP01.FRENCH.720p.WEBRIP.XVID-STR` Gets recognized as a pack for the 1st season when its an ep for the 1st ep of the 1st season

**Comment by duramato** [comment]
![image](https://cloud.githubusercontent.com/assets/10121067/17831537/5741a1ac-66e3-11e6-9dd0-2cb32511fd2c.png)

All resuls there , exclueding: Between.S01.720p.HDTV.x264-TvT, Между./.Between.[S01].(2015).HDTVRip.720p.|.Baibako ,Между./.Between.[S01].(2015).HDTVRip.720p.|.NewStudio ,Между./.Between.[S01].(2015).HDTVRip.|.NewStudio  , are getting wrongfully tagged as season packs

**Comment by ratoaq2** [comment]
please, paste the release name. I can't copy screenshots

**Comment by duramato** [comment]
```
Между./.Between.[01х01-03.из.06].(2015).HDTVRip.720p.|.NewStudio
Между./.Between.[01х01-05.из.06].(2015).HDTVRip.720p.|.NewStudio
Между./.Between.[01х01-04.из.06].(2015).HDTVRip.720p.|.Baibako
Между./.Between.[01х01.из.6].(2015).HDTVRip.720p.|.Baibako
Между./.Between.[01х01-04.из.06].(2015).HDTVRip.720p.|.NewStudio
Между./.Between.[01х01-03.из.06].(2015).HDTVRip.720p.|.Baibako
Между./.Between.[01х01-05.из.06].(2015).HDTVRip.720p.|.Baibako
Между./.Between.[01х01-02.из.06].(2015).HDTVRip.720p.|.Baibako
Между./.Between.[01х01-02.из.06].(2015).HDTVRip.720p.|.NewStudio
Между./.Between.[01х01-05.из.06].(2015).HDTVRip.|.BaibaKo
Между./.Between.[01х01-05.из.06].(2015).HDTVRip.|.NewStudio
Между./.Between.[01х01-04.из.06].(2015).HDTVRip.|.BaibaKo
Между./.Between.[01х01-04.из.06].(2015).HDTVRip.|.NewStudio
Между./.Between.[01х01-03.из.06].(2015).HDTVRip.|.NewStudio
Между./.Between.[01х01-02.из.06].(2015).HDTVRip.|.NewStudio
Между./.Between.[01х01-03.из.06].(2015).HDTVRip.|.BaibaKo
Между./.Between.[01х01-02.из.06].(2015).HDTVRip.|.BaibaKo
```

**Comment by ratoaq2** [comment]
What are these characters in the middle of the numbers? does it mean something?

What do you expect from this? -> `Между./.Between.[01х01-03.из.06].(2015).HDTVRip.720p.|.NewStudio`

What's the show, season, episodes, and release_group?

**Comment by duramato** [comment]
**Show:** Between or Между , russian releases like italian tend to have the original and translated
**Numbering:** `[01х01-03.из.06]`  reads: `01х` First season , `01-03` ep 1-3 , `.из.06` of a total of 06
**Year:** (2015)
**Source:** HDTVRip
**Resolution:** 720p
**Group:** NewStudio

A "normal" russian release like `,Между./.Between.[S01].(2015).HDTVRip.720p.|.NewStudio `for example gets detected correctly afaik

**Comment by duramato** [comment]
`Panorama.S64E13.Is.Steel.Worth.Saving.1080p.HDTV.AAC.x264-MVGroup.org/BBC.Panorama.2016.Is.Steel.Worth.Saving.1080p.HDTV.x264.AAC.MVGroup.org.mkv`
It's the file `BBC.Panorama.2016.Is.Steel.Worth.Saving.1080p.HDTV.x264.AAC.MVGroup.org.mkv` inside of the `Panorama.S64E13.Is.Steel.Worth.Saving.1080p.HDTV.AAC.x264-MVGroup.org` directory. 
**_Issue:_** the group MVGroup.org does not get detected as group, and no group gets detected. 

_Note:_ I think this happens becouse guessit returns it as website, and I think Medusa should be using the website tag guessit returns when the group tag is not present.

**Comment by duramato** [comment]
`The.Night.Of.S01E05.720p.HDTV.450MB.-.NBY` 
**Detected Group:** NB
**_Should be:_** NBY

**Comment by duramato** [comment]
```
Unable to match Counting.On.S02E04.Meet.The.Parents.HDTV.x264-[NY2].-.[SRIGGA] to a show in your database. Parser result: title: Counting On, season: 2, episode: [4], episode_title: Meet The Parents, format: HDTV, video_codec: h264, release_group: NY2, type: episode, absolute_episode: [], quality: Unknown
```

```
Unable to match Music.For.Misfits.The.Story.Of.Indie.S01E02.WEB.h264-ROFL to a show in your database. Parser result: title: Music For Misfits The Story Of Indie, season: 1, episode: [2], format: WEB-DL, video_codec: h264, release_group: ROFL, type: episode, absolute_episode: [], quality: Unknown
```

```
Unable to match BrainDead.S01E12.Talking.Points.Toward.a.Wholistic.View.of.Activism.in.Government.720p.WEB-DL.DD5.1.H.264-ViSUM to a show in your database. Parser result: title: BrainDead, season: 1, episode: [12], episode_title: Talking Points Toward a Wholistic View of Activism in Government, screen_size: 720p, format: WEB-DL, audio_codec: DolbyDigital, audio_channels: 5.1, video_codec: h264, release_group: ViSUM, type: episode, absolute_episode: [], quality: Unknown
```

Quality is not getting detected `quality: Unknown`

**Comment by medariox** [comment]
```
 python tests/report_guessit.py My.Show.S13E22.720p.HDTV.x264-NBY.mkv
# guessit: 2.1.0.dev0  rebulk: 0.7.3
? My.Show.S13E22.720p.HDTV.x264-NBY.mkv
: title: My Show
  season: 13
  episode: 22
  screen_size: 720p
  format: HDTV
  video_codec: h264
  release_group: NB
  container: mkv
  mimetype: video/x-matroska
  type: episode
```
Group should be NB**Y**

**Comment by medariox** [comment]
```
 python tests/report_guessit.py [.www.rato.com.].-.Snooze.and.Go.Sleep.S03E02.1080p.HEVC.x265-MeGusta
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? [.www.rato.com.].-.Snooze.and.Go.Sleep.S03E02.1080p.HEVC.x265-MeGusta
: release_group: www.rato.com
  title: Snooze and Go Sleep
  season: 3
  episode: 2
  screen_size: 1080p
  video_codec: h265
  type: episode
```
Group should be MeGusta

**Comment by duramato** [comment]
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Marvels.Agents.of.S.H.I.E.L.D.S04E01.The.Ghost.1080P.WEB-DL.DD5
: title: Marvels Agents of S.H.I.E.L.D.
  season: 4
  episode: 1
  episode_title: The Ghost
  screen_size: 1080p
  format: WEB-DL
  release_group: DD5
  type: episode
```

Groud should be none

**Comment by medariox** [comment]
@duramato 
DD5 doesn't exist at all. The nearest thing that comes to it is DD5.1...

**Comment by duramato** [comment]
@medariox long release names get cut off on certain sites, like tpb ie, guessit should just threat DD5 as superflous info

**Comment by duramato** [comment]
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Abandoned.2016.S01E04.California.Water.Supply.720p.VICE.WEBRip.AAC2.0.H.264-RTN.mkv.-.[SRIGGA]
: title: Abandoned
  alias: Abandoned 2016
  year: 2016
  season: 1
  episode: 4
  episode_title: California Water Supply
  screen_size: 720p
  format: WEBRip
  audio_codec: AAC
  audio_channels: 2.0
  video_codec: h264
  container: MKV
  release_group: SRIGGA
  type: episode
```

Release group is wrong , should be RTN

**Comment by duramato** [comment]
```Quantico.S02E01.Kudove.720p.WEB-DL.DD5.1.H.264-AG.nzb``` 

```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Quantico.S02E01.Kudove.720p.WEB-DL.DD5.1.H.264-AG.nzb
: title: Quantico
  season: 2
  episode: 1
  episode_title: Kudove
  screen_size: 720p
  format: WEB-DL
  audio_codec: DolbyDigital
  audio_channels: 5.1
  video_codec: h264
  release_group: AG.nzb
  type: episode
```
The wrong group is detected, should be AG

**Comment by fernandog** [comment]
**Wrong group when title has year:**

This also happens for show : 
`Bull.2016.S01E02.1080p.HDTV.X264-DIMENSION[rarbg]\Bull.2016.S01E02.1080p.HDTV.X264-DIMENSION.mkv`

```
python report_guessit.py "/media/SAMSUNG/media/downloaded/series/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION[rarbg]/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION.mkv"
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? /media/SAMSUNG/media/downloaded/series/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION[rarbg]/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION.mkv
: title: The Flash
  alias: The Flash 2014
  year: 2014
  season: 3
  episode: 1
  screen_size: 1080p
  format: HDTV
  video_codec: h264
  release_group: rarbg
  container: mkv
  mimetype: video/x-matroska
  type: episode
```

original guessit:
```
guessit "/media/SAMSUNG/media/downloaded/series/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION[rarbg]/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION.mkv"
For: /media/SAMSUNG/media/downloaded/series/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION[rarbg]/The.Flash.2014.S03E01.1080p.HDTV.X264-DIMENSION.mkv
GuessIt found: {
    "title": [
        "The Flash",
        "DIMENSION"
    ],
    "year": 2014,
    "season": 3,
    "episode": 1,
    "screen_size": "1080p",
    "format": "HDTV",
    "video_codec": "h264",
    "release_group": "rarbg",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

```

**Comment by fernandog** [comment]
```
$ python tests/report_guessit.py "D:\TV\BRITISH COMEDY\Black Books\Season 01\Black Books S01E06 DVD-RIP x264-S4L.mkv"
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? D:\TV\BRITISH COMEDY\Black Books\Season 01\Black Books S01E06 DVD-RIP x264-S4L.mkv
: title: Black Books
  season: [1, 4]
  episode: 6
  format: DVD
  video_codec: h264
  episode_title: L
  container: mkv
  mimetype: video/x-matroska
  type: episode
```
from @wimpyrbx

**Comment by ratoaq2** [comment]
Can we organise another issue for this issue? With a checklist where I can cross when fixed.

**Comment by duramato** [comment]
@ratoaq2 make an issue with a list of checkboxes and a link to comments here, or maybe just edit fernandog's OP with the suggestion like:

[x] https://github.com/pymedusa/Medusa/issues/810#issuecomment-254507314

**Comment by fernandog** [comment]
see first comment in this issue

**Comment by medariox** [comment]
Wrong group for: ```Great.Show.S01E02.Chestbun.720p.HBO.WEBRip.DD5.1.H.264```

![guessit result](https://snapr.pw/i/fb55d662c0.png)

Group: HBO
Should be: None

**Comment by duramato** [comment]
Wrong ep title and air date
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? VICE.News.Tonight.2016.10.21.1080p.HBO.WEBRip.AAC2.0.H.264-monkee.mkv
: title: VICE News Tonight
  year: 2016
  episode_title: 10 21
  screen_size: 1080p
  format: WEBRip
  audio_codec: AAC
  audio_channels: 2.0
  video_codec: h264
  release_group: monkee
  container: mkv
  mimetype: video/x-matroska
  type: episode
```

**Comment by duramato** [comment]
Release group should be none, HBO should be guessit's `other` tag
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Westworld.S01E04.1080p.HBO.WEBRip.DD5.1.H.264
: title: Westworld
  season: 1
  episode: 4
  screen_size: 1080p
  release_group: HBO
  format: WEBRip
  audio_codec: DolbyDigital
  audio_channels: 5.1
  video_codec: h264
  type: episode
```

**Comment by duramato** [comment]
Release group should be `Belex`

```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Westworld.S01E04.720p.HDTV.x264-Belex.-.Dual.Audi
: title: Westworld
  season: 1
  episode: 4
  screen_size: 720p
  format: HDTV
  video_codec: h264
  release_group: Belex Audi
  type: episode
```

**Comment by ratoaq2** [comment]
Release name is not complete. Maybe when guessit becomes skynet that will start working

**Comment by duramato** [comment]
Which one is not complete?

**Comment by duramato** [comment]
Title should be: **17.Mgnovenij.vesni** , isntead the 17 from it goes to the episode list
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? 17.Mgnovenij.vesni.01.of.12.(Rus).avi
: episode: [17, 1]
  title: Mgnovenij vesni
  episode_count: 12
  language: ru
  container: avi
  mimetype: video/x-msvideo
  type: episode
```

**Comment by ratoaq2** [comment]
Do you have this show in your show list?

**Comment by duramato** [comment]
Wrong group:
**Detected:** Season
**Should be:**  None
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? The.Missing.Series.1.[HD].720p.mp4.*Season.Repack*.hdtv.x264
: title: The Missing
  season: 1
  other: ['HD', 'Proper']
  screen_size: 720p
  container: MP4
  release_group: Season
  proper_count: 1
  proper_tag: REPACK
  format: HDTV
  video_codec: h264
  type: episode
```
And
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? The.Missing.Series.1.mp4.*Season.Repack*.hdtv.x264
: title: The Missing
  season: 1
  container: MP4
  release_group: Season
  other: Proper
  proper_count: 1
  proper_tag: REPACK
  format: HDTV
  video_codec: h264
  type: episode
```

**Comment by duramato** [comment]
Release group is wrong, should be **DHD**
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? National.Geographic.Documentaries.S2016E15.720p.HDTV.x264.Mammoth.Back.from.the.Dead-DHD.mkv
: title: National Geographic Documentaries
  season: 2016
  year: 2016
  episode: 15
  screen_size: 720p
  format: HDTV
  video_codec: h264
  release_group: Mammoth.Back.from.the.Dead-DHD
  container: mkv
  mimetype: video/x-matroska
  type: episode
```

**Comment by duramato** [comment]
Scene release:
Season 01
Episode 06
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Dead.Set.On.Life.S01.720p.HDTV.DD5.1.x264-YesTV/dead.set.on.life.0106.720p-yestv.mkv
: title: Dead Set On Life
  season: 1
  screen_size: 720p
  format: HDTV
  audio_codec: DolbyDigital
  audio_channels: 5.1
  video_codec: h264
  release_group: YesTV
  container: mkv
  mimetype: video/x-matroska
  type: episode
```

**Comment by duramato** [comment]
Wrong group, should be SQUEAK
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? National.Geographic.Documentaries.S2015E30.720p.HDTV.x264.Youtube.Revolution-SQUEAK
: title: National Geographic Documentaries
  season: 2015
  year: 2015
  episode: 30
  screen_size: 720p
  format: HDTV
  video_codec: h264
  release_group: Youtube.Revolution
  type: episode
```

**Comment by duramato** [comment]
Wrong release group, should be none.

```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? The.Walking.Dead.S07E04.Service.1080p.AMZN.WEBRip.DD+5.1.x264
: title: The Walking Dead
  season: 7
  episode: 4
  episode_title: Service
  screen_size: 1080p
  release_group: AMZN
  format: WEBRip
  audio_codec: AC3
  audio_channels: 5.1
  video_codec: h264
  video_encoder: x264
  type: episode
```

**Comment by ratoaq2** [comment]
Amzn means Amazon? If yes, then it's an easy fix

**Comment by duramato** [comment]
Yes , it's the same as [this](https://github.com/pymedusa/Medusa/issues/810#issuecomment-255558111) the tag can very depending on the network

**Comment by medariox** [comment]
Wrong release group:
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Musaigen.no.Phantom.World.S01E01-E13.Bluray.MKV.h264.1080p.FLAC2-jsum
: title: Musaigen no Phantom World
  season: 1
  episode: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  format: BluRay
  container: MKV
  video_codec: h264
  screen_size: 1080p
  release_group: FLAC2
  type: episode
```
Should be jsum instead of FLAC2.

**Comment by OmgImAlexis** [comment]
Ref: https://github.com/pymedusa/Medusa/issues/1581

**Comment by duramato** [comment]
Should have a date tag
```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Panorama.(2016).09.05.Sellafields.Nuclear.Safety.Failings.720p.HDTV.x264.C4TV.eztv.mkv
: title: Panorama
  year: 2016
  episode_title: 09 05 Sellafields Nuclear Safety Failings
  screen_size: 720p
  format: HDTV
  video_codec: h264
  video_encoder: x264
  release_group: C4TV
  container: mkv
  mimetype: video/x-matroska
  type: episode
```

**Comment by duramato** [comment]
Wrong season tag, there shouldn't be any.

```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? A Very British Murder with Lucy Worsley Series 1 (2013) XVID Series Repack/A Very British Murder with Lucy Worsley 2of3 (30 Ssep 2013).avi
: title: A Very British Murder with Lucy Worsley
  release_group: Series
  season: [1, 2013]
  video_codec: XviD
  other: Proper
  proper_count: 1
  proper_tag: REPACK
  episode: 2
  episode_count: 3
  year: 2013
  container: avi
  mimetype: video/x-msvideo
  type: episode
```

**Comment by duramato** [comment]
Title is wrong should be `LoveSick` and `Scrotal Recall` and alternate_title

```
# guessit: 2.1.1.dev0  rebulk: 0.7.6
? Lovesick.AKA.Scrotal.Recall.S02E01.720p.WEBRip.x264 eSc.mp4
: title: Lovesick AKA Scrotal Recall
  season: 2
  episode: 1
  screen_size: 720p
  format: WEBRip
  video_codec: h264
  video_encoder: x264
  release_group: eSc
  container: mp4
  mimetype: video/mp4
  type: episode
```

**Comment by ratoaq2** [comment]
Only an AI can fix supergonkas' guessit issues

**Comment by duramato** [comment]
Wrong title should `Swedish Dicks`
```
# guessit: 2.1.1.dev0  rebulk: 0.8.3.dev0
? Swedish.Dicks.S01.1080p.WEB-DL.AAC2.0.H264-HDB
: language: sv
  title: Dicks
  season: 1
  screen_size: 1080p
  format: WEB-DL
  audio_codec: AAC
  audio_channels: 2.0
  video_codec: h264
  release_group: HDB
  type: episode
  parsing_time: 0.317012071609
```

**Comment by medariox** [comment]
```
# guessit: 2.1.1.dev0  rebulk: 0.8.3.dev0
? Bounty.(2016).S01E02.HDTV.SubtituladoEsp.SC
: title: Bounty
  alias: Bounty 2016
  year: 2016
  season: 1
  episode: 2
  format: HDTV
  release_group: SubtituladoEsp
  type: episode
  parsing_time: 0.325940132141
```
Wrong group. Should be ```SC```

**Comment by duramato** [comment]
```

**Comment by duramato** [comment]
Wrong `episode_details` , the `Special` is part of the title.
g ```
# guessit: 2.1.1.dev0  rebulk: 0.8.3.dev0
? Special.Ops.Mission.Season.S01.DVD.x265.10bit.AAC.2.0
: episode_details: Special
  title: Special Ops Mission Season
  season: 1
  format: DVD
  video_codec: h265
  video_encoder: x265
  video_profile: 10bit
  audio_codec: AAC
  audio_channels: 2.0
  type: episode
  parsing_time: 0.48646903038
```

**Comment by ratoaq2** [comment]
Too big. I can't easily reply old comments with invalid release names (typos, etc)
Report them separately (or grouped when it makes sense) and flag it as `guessit`
